#!/bin/bash

CURRENT_VERSION="16.0.5"

if [[ ${1} == "" ]]; then
    VERSION=$CURRENT_VERSION
else
    VERSION=$1
fi

NEXTCLOUD_VERSION=$VERSION podman build --no-cache -t sotolitolabs-nextcloud:$VERSION .

podman tag sotolitolabs-nextcloud:$VERSION  sotolitolabs-nextcloud:latest

