#!/bin/bash

# Setup script for nextcloud

HOST_DIR="/var/sotolito"

if [[ "${1}" != "" ]]; then
  HOST_DIR=$1
fi

podman run --rm --name="sotolito-nextcloud-setup"  \
           -v $HOST_DIR:/var/sotolito \
           sotolitolabs-nextcloud

