#!/bin/bash

VERSION=$1
VERSION=1.16.1-r0
docker build --no-cache  -t sotolitolabs-alpine-arm-nginx-setup:$VERSION .

docker tag sotolitolabs-alpine-arm-nginx-setup:$VERSION  sotolitolabs-alpine-arm-nginx-setup:latest

#docker tag sotolitolabs-alpine-arm-nginx-setup:$VERSION  hub.enelserver.com:5000/sotolitolabs-alpine-arm-nginx-setup:$VERSION
#docker tag sotolitolabs-alpine-arm-nginx-setup:$VERSION hub.enelserver.com:5000/sotolitolabs-alpine-arm-nginx-setup:latest
#docker push hub.enelserver.com:5000/sotolitolabs-alpine-arm-nginx-setup:latest
#docker push hub.enelserver.com:5000/sotolitolabs-alpine-arm-nginx-setup:$VERSION



