#!/bin/bash

VERSION=$1
VERSION=7.1.15-r0
docker build --no-cache -t sotolitolabs-alpine-arm-php-fpm:$VERSION .

docker tag sotolitolabs-alpine-arm-php-fpm:$VERSION  sotolitolabs-alpine-arm-php-fpm:latest


