#!/bin/bash

source ../../lib/containers.shlib
source systemd/nginx.env.${HOSTTYPE}

VERSION="1.14.2-r4"
if [[ "${1}" != "" ]]; then
  VERSION=$1
fi

IMAGE_NAME="sotolitolabs-alpine-${HOSTTYPE}-nginx"

echo "Creating nginx image ${IMAGE_NAME}"

SUDO=$(check_if_sudo $CONTAINER_USER)

echo "COMMAND: $SUDO /usr/bin/podman build --no-cache  -t $IMAGE_NAME:$VERSION ${BUILD_DIR}"
$SUDO /usr/bin/podman build --no-cache  -t $IMAGE_NAME:$VERSION $BUILD_DIR
$SUDO /usr/bin/podman tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

