FROM  alpine
MAINTAINER Alejandro Acosta "alxacostaa@gmail.com"


RUN apk add python3 && \
apk add py3-pip && \
apk add openjdk10-jdk openjdk10-jre-headless

RUN pip3 install --upgrade pip
RUN pip3 install pyspark


