#!/bin/bash

source ../../lib/containers.shlib
source systemd/mariadb.env.${HOSTTYPE}

BUILD_DIR=$(pwd)
VERSION=10.4.8
if [[ "${1}" != "" ]]; then
  VERSION=$1
fi

IMAGE_NAME="sotolitolabs-alpine-${HOSTTYPE}-mariadb"

echo "Creating mariadb image ${IMAGE_NAME}"

SUDO=$(check_if_sudo $CONTAINER_USER)

echo "COMMAND: $SUDO /usr/bin/podman build --no-cache  -t $IMAGE_NAME:$VERSION ${BUILD_DIR}"
$SUDO /usr/bin/podman build --no-cache  -t $IMAGE_NAME:$VERSION $BUILD_DIR
$SUDO /usr/bin/podman tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest



