#!/bin/sh

# This script should be run inside the mariadb container

echo "Creating directories"
chown mysql.mysql /var/lib/mysql
mkdir /var/lib/mysql/mysql
chown mysql.mysql /var/lib/mysql/mysql
mkdir /var/lib/mysql/test
chown mysql.mysql /var/lib/mysql/test
mkdir /run/mysqld
chown mysql.mysql /run/mysqld
mkdir /var/tmp/mariadb
chown mysql.mysql /var/tmp/mariadb

cp /my.cnf /etc/mysql
chown mysql.mysql /etc/mysql/my.cnf

mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
su mysql -c mysqld &
sleep 5

echo "Granting privileges for external access"
echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'  identified by '${MYSQL_ROOT_PASSWORD}';" > /grant.sql 
echo "flush privileges;" >> /grant.sql
mysql -u root  < /grant.sql

/usr/bin/mysqladmin -u root password $MYSQL_ROOT_PASSWORD
