#!/bin/bash

docker run -ti --rm --name="mariadbsetup" -p 3306:3306    \
           -v /var/sotolito/vols/mariadb/var/lib/mysql/:/var/lib/mysql/ \
           -v /var/sotolito/vols/mariadb/etc/mysql:/etc/mysql \
           -v /var/sotolito/vols/mariadb/run/mysqld:/run/mysqld/ \
           -e "LANG=en_US.UTF-8" \
           -e "LC_MESSAGES=POSIX" \
           -e "LANGUAGE=en_US.UTF-8" \
           -e "LC_CTYPE=en_US.UTF-8" \
           -e "MYSQL_ROOT_PASSWORD=sotolito" \
           sotolitolabs-alpine-arm-mariadb  /doinstall

