#!/bin/bash

# Setup the mariadb container environment

source ../../lib/containers.shlib
source systemd/mariadb.env.${HOSTTYPE}

echo "Setting up the mariadb container environment"

MY_PW="sotolito"
if [[ "${1}" != "" ]]; then
  MY_PW=$1
fi

SUDO=$(check_if_sudo $CONTAINER_USER)
$SUDO /usr/bin/mkdir -p {$VOLUME_DIR/var/lib/mysql,$VOLUME_DIR/etc/mysql,$VOLUME_DIR/run/mysqld,$VOLUME_DIR/var/tmp/mariadb}
sudo cp my.cnf.podman $VOLUME_DIR/etc/mysql/my.cnf
sudo chown $CONTAINER_USER:$CONTAINER_GROUP $VOLUME_DIR/etc/mysql/my.cnf

#Have to use podman unshare so the mysql (UID=100, GID=101) user inside the container can write to the directory
$SUDO podman unshare chown ${ALPINE_MYSQL_UID}:${ALPINE_MYSQL_GID} $VOLUME_DIR/var/lib/mysql
$SUDO podman unshare chown ${ALPINE_MYSQL_UID}:${ALPINE_MYSQL_GID} $VOLUME_DIR/run/mysqld
$SUDO podman unshare chown ${ALPINE_MYSQL_UID}:${ALPINE_MYSQL_GID} $VOLUME_DIR/var/tmp/mariadb

echo "Running setup container"

$SUDO podman run -ti --rm --ulimit nofile=1024:65535 --name="mariadbsetup"   \
  -v $HOST_DIR/vols/mariadb/var/lib/mysql/:/var/lib/mysql/ \
  -v $HOST_DIR/vols/mariadb/var/tmp/mariadb/:/var/tmp/mariadb/ \
  -v $HOST_DIR/vols/mariadb/etc/mysql:/etc/mysql \
  -v $HOST_DIR/vols/mariadb/run/mysqld:/run/mysqld/ \
  -e LANG="en_US.UTF-8"\
  -e LC_MESSAGES=POSIX \
  -e LANGUAGE=en_US.UTF-8 \
  -e LC_CTYPE=en_US.UTF-8 \
  -e MYSQL_ROOT_PASSWORD="$MY_PW"\
  $IMAGE_NAME  /doinstall

echo "Setup systemd unit"
sudo cp ${BUILD_DIR}/systemd/mariadb.env.${ARCH} /etc/sotolito/
sudo cp ${BUILD_DIR}/systemd/sotolito-mariadb.service /usr/lib/systemd/system/

