#!/bin/bash

source ../../lib/containers.shlib
source systemd/mariadb.env.${HOSTTYPE}

echo "Creating Container User"
sudo groupadd $CONTAINER_GROUP
sudo useradd -m -g $CONTAINER_GROUP -d /home/$CONTAINER_USER -c 'Sotolito sotolito-mariadb Container User' -s /bin/bash $CONTAINER_USER 

./build
./runsetup $1


echo "Tu run it execute: ./runmaria"
