#!/bin/bash

VERSION=7.1.15-r0
docker build --no-cache  -t sotolitolabs-alpine-arm-php-fpm-setup:$VERSION .

docker tag sotolitolabs-alpine-arm-php-fpm-setup:$VERSION  sotolitolabs-alpine-arm-php-fpm-setup:latest
