#!/bin/bash

docker run -d   --name="postgresql" -h postgresql -v /var/sotolito/vols/postgresql/10/:/var/lib/postgresql/10/  -v /var/sotolito/vols/postgresql/10/run/:/run/postgresql/: sotolitolabs-alpine-arm-postgresql


